services:
  mongodb:
    image: mongo:latest
    container_name: devops_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: devops_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - devops_network

  app:
    build: .
    container_name: devops_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017/devops_db?authSource=admin
    networks:
      - devops_network

volumes:
  mongodb_data:

networks:
  devops_network:
    driver: bridge
